services:

  database:
    image: postgres:latest
    container_name: rental_system_db
    ports:
      - ${DB_PORT}:8080
    volumes:
      - ./database_data:/var/lib/postgres/data
      - ./database-roles-init.sql:/docker-entrypoint-initdb.d/init1.sql
      - ./database-init.sql:/docker-entrypoint-initdb.d/init2.sql
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080